# permissions to do edit keystoneservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoneserver-editor-role
rules:
- apiGroups:
  - openstack.osop.org
  resources:
  - keystoneservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.osop.org
  resources:
  - keystoneservers/status
  verbs:
  - get
  - patch
  - update
